### ISSUE TITLE
Document <optgroup> support

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2.github.io#115]
https://github.com/sweetalert2/sweetalert2/pull/1985

1. Add `<optgroup>` support info to https://sweetalert2.github.io/#input-options
2. Improve the https://sweetalert2.github.io/#input-select example by adding `<optgroup>`

**Comment by tiagostutz** [comment]
Hi!
If nobody takes this one until friday, I'm doing to do it on my Open Source Friday.

**Comment by limonte** [comment]
Hey @tiagostutz 

I added your name and userpic to the list of SweetAlert2's Sponsors. In that list we have only people who are contributing with $19/month or more, but your contributions are very useful so I decided to break my rules for you.

Thank you so much for your support, both financial and with your code contributions! I really appreciate it!

**Comment by tiagostutz** [comment]
W O W!!! Thank you so much @limonte ! That's been such an honor to contribute to this amazing project. You are a good example of OSS maintainer and community manager.

I hope contributing more to this and other projects we may have in common in future. BTW, if you have other projects that need help let me know because I can suggest them to friends and partners that are willing to help on OSS.

**Comment by limonte** [comment]
> W O W!!! Thank you so much @limonte ! That's been such an honor to contribute to this amazing project. You are a good example of OSS maintainer and community manager.

Thank you for the kind words, I appreciate that and doing my best here!

> I hope contributing more to this and other projects we may have in common in future. BTW, if you have other projects that need help let me know because I can suggest them to friends and partners that are willing to help on OSS.

https://github.com/sweetalert2/sweetalert2-themes/issues/13 would be the interesting task to handle
