### ISSUE TITLE
IE11 should be supported

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2.github.io#3]
By making the docs work in IE11 we will prevent users' confusions about supporting IE11 ( https://github.com/sweetalert2/sweetalert2/issues/536)

Also, it's handy to quickly test docs page with IE11 and ensure everything works in it like in other browsers.

**Comment by ChriStef** [comment]
...so in order to success a working IE11 swal example is to syntax not to use ES6  arrow ()=> but a function. Does this have an impact to the standard working of swal in chrome/firefox?

**Comment by zenflow** [comment]
@ChriStef 

> ...so in order to success a working IE11 swal example is to syntax not to use ES6 arrow ()=> but a function. 

Yes, also you need to load your own Promise polyfill, and you cannot use the async/await or destructuring features of js, or some other features. 

You should learn what the new JS features are, and watch out for them in any code (not just SweetAlert2) if you need to support IE11. You don't need to worry about this for Chrome or Firefox or Safari or Edge because they are [evergreen](http://eisenbergeffect.bluespire.com/evergreen-browsers/).

Or, as I would recommend, use [Babel](https://babeljs.io/docs/setup/) to transpile your code down to ES5, and then you can use all the latest and greatest features without worrying about supported browsers. If you don't have any build system already, go with `babel-cli` (click "CLI" under "Babel built-ins"). It is not as hard as you might think.

**Comment by zenflow** [comment]
I came here to say we should probably be transpiling the source for this project down to ES5.

**Comment by zenflow** [comment]
@ChriStef Oh, and the only plugin or preset you really need is `babel-preset-env`.

**Comment by ChriStef** [comment]
Thanks @zenflow this is very helpful, babel it s a saver. I did what you suggest and now I have a working beautiful demo in ie11. Thank you a million keep up the good work...
